package com.itechro.cas.commons.constants;

public class PrivilegeCode {

    public static class SYSTEM {
        public static final String ADMIN_USER_DELEGATED_AUTHORITY_APPROVE_OR_REJECT = "ADMIN.USER.DELEGATED.AUTHORITY.APPROVE.OR.REJECT";


        public static final String ICAS_SETTINGS_USER_DA_VIEW = "ICAS.SETTINGS.USER.DA.VIEW";
        public static final String ICAS_SETTINGS_USER_DA_ADD = "ICAS.SETTINGS.USER.DA.ADD";
        public static final String ICAS_SETTINGS_USER_DA_EDIT = "ICAS.SETTINGS.USER.DA.EDIT";

        public static final String ICAS_SETTINGS_ROLE_VIEW = "ICAS.SETTINGS.ROLE.VIEW";
        public static final String ICAS_SETTINGS_ROLE_ADD = "ICAS.SETTINGS.ROLE.ADD";
        public static final String ICAS_SETTINGS_ROLE_EDIT = "ICAS.SETTINGS.ROLE.EDIT";
        public static final String ICAS_SETTINGS_MURAPADAYA_RESET = "ICAS_SETTINGS_MURAPADAYA_RESET";
        public static final String ICAS_WEB_AUDIT_VIEW = "ICAS.SETTINGS.WEB.AUDIT.VIEW";

        public static final String ICAS_SETTINGS_LEAD_VIEW = "ICAS.SETTINGS.LEAD.VIEW";
        public static final String ICAS_SETTINGS_MY_BRANCH_LEAD_VIEW = "ICAS.SETTINGS.LEAD.MY.BRANCH.VIEW";
        public static final String ICAS_SETTINGS_LEAD_CUSTOMER_VIEW = "ICAS.SETTINGS.LEAD.CUSTOMER.VIEW";
        public static final String ICAS_SETTINGS_LEAD_ADD = "ICAS.SETTINGS.LEAD.ADD";
        public static final String ICAS_SETTINGS_LEAD_EDIT = "ICAS.SETTINGS.LEAD.EDIT";
        public static final String ICAS_SETTINGS_LEAD_STATUS_UPDATE = "ICAS.SETTINGS.LEAD.STATUS.UPDATE";

        public static final String ICAS_SETTINGS_FACILITY_PAPER_CREDIT_RISK_COMMENT_ADD = "ICAS.SETTINGS.FACILITY.PAPER.CREDIT.RISK.COMMENT.ADD";

        public static final String ICAS_SETTINGS_FACILITY_PAPER_VIEW = "ICAS.SETTINGS.FACILITY.PAPER.VIEW";
        public static final String ICAS_SETTINGS_FACILITY_PAPER_ADD = "ICAS.SETTINGS.FACILITY.PAPER.ADD";
        public static final String ICAS_SETTINGS_FACILITY_PAPER_EDIT = "ICAS.SETTINGS.FACILITY.PAPER.EDIT";

        public static final String ICAS_SETTINGS_CREDIT_FACILITY_TYPE_VIEW = "ICAS.SETTINGS.CREDIT.FACILITY.TYPE.VIEW";
        public static final String ICAS_SETTINGS_CREDIT_FACILITY_TYPE_ADD = "ICAS.SETTINGS.CREDIT.FACILITY.TYPE.ADD";
        public static final String ICAS_SETTINGS_CREDIT_FACILITY_TYPE_EDIT = "ICAS.SETTINGS.CREDIT.FACILITY.TYPE.EDIT";

        public static final String ICAS_SETTINGS_CREDIT_FACILITY_TEMPLATE_VIEW = "ICAS.SETTINGS.CREDIT.FACILITY.TEMPLATE.VIEW";
        public static final String ICAS_SETTINGS_CREDIT_FACILITY_TEMPLATE_ADD = "ICAS.SETTINGS.CREDIT.FACILITY.TEMPLATE.ADD";
        public static final String ICAS_SETTINGS_CREDIT_FACILITY_TEMPLATE_EDIT = "ICAS.SETTINGS.CREDIT.FACILITY.TEMPLATE.EDIT";

        public static final String ICAS_SETTINGS_SUPPORTING_DOC_VIEW = "ICAS.SETTINGS.SUPPORTING.DOC.VIEW";
        public static final String ICAS_SETTINGS_SUPPORTING_DOC_ADD = "ICAS.SETTINGS.SUPPORTING.DOC.ADD";
        public static final String ICAS_SETTINGS_SUPPORTING_DOC_EDIT = "ICAS.SETTINGS.SUPPORTING.DOC.EDIT";

        public static final String ICAS_SETTINGS_UPC_SECTION_VIEW = "ICAS.SETTINGS.UPC.SECTION.VIEW";
        public static final String ICAS_SETTINGS_UPC_SECTION_ADD = "ICAS.SETTINGS.UPC.SECTION.ADD";
        public static final String ICAS_SETTINGS_UPC_SECTION_EDIT = "ICAS.SETTINGS.UPC.SECTION.EDIT";

        public static final String ICAS_SETTINGS_UPC_TEMPLATE_VIEW = "ICAS.SETTINGS.UPC.TEMPLATE.VIEW";
        public static final String ICAS_SETTINGS_UPC_TEMPLATE_ADD = "ICAS.SETTINGS.UPC.TEMPLATE.ADD";
        public static final String ICAS_SETTINGS_UPC_TEMPLATE_EDIT = "ICAS.SETTINGS.UPC.TEMPLATE.EDIT";

        public static final String ICAS_SETTINGS_UPM_GROUP_VIEW = "ICAS.SETTINGS.UPM.GROUP.VIEW";
        public static final String ICAS_SETTINGS_UPM_GROUP_ADD = "ICAS.SETTINGS.UPM.GROUP.ADD";
        public static final String ICAS_SETTINGS_UPM_GROUP_EDIT = "ICAS.SETTINGS.UPM.GROUP.EDIT";

        public static final String ICAS_SETTINGS_WORKFLOW_TEMPLATE_VIEW = "ICAS.SETTINGS.WORKFLOW.TEMPLATE.VIEW";
        public static final String ICAS_SETTINGS_WORKFLOW_TEMPLATE_ADD = "ICAS.SETTINGS.WORKFLOW.TEMPLATE.ADD";
        public static final String ICAS_SETTINGS_WORKFLOW_TEMPLATE_EDIT = "ICAS.SETTINGS.WORKFLOW.TEMPLATE.EDIT";

    }

}
