package com.itechro.cas.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

@Component
public class CasProperties {

    @Value("${private.key.der.absolute.path}")
    private String privateKeyDerAbsolutePath;

    @Value("${public.key.der.absolute.path}")
    private String publicKeyDerAbsolutePath;

    @Value("${public.key.pem.absolute.path}")
    private String publicKeyPemAbsolutePath;

    @Value("${api.prefix}")
    private String apiPrefix;

    @Value("${spring.mvc.static-path-pattern}")
    private String staticResourcesPath;

    @Value("${security.enabled}")
    private Boolean isSecurityEnabled;

    @Value("${apps.cas.image.upload.max.size.mb}")
    private String imageUploadMaxSizeMB;

    @Value("${apps.cas.image.allowed.extensions}")
    private String imageUploadAllowedExtensions;

    @Value("${apps.cas.application.code}")
    private String applicationCode;

    @Value("${ldap.server.url}")
    private String ldapServerURL;

    @Value("${ldap.user.context}")
    private String ldapUserContext;

    @Value("${apps.cache.hazelcast.tcpip.enabled}")
    private String tcpIpConfigEnabled;

    @Value("${apps.cache.hazelcast.nodes}")
    private String nodesInfo;

    @Value("${apps.cas.application.approve.restricted.for.own.user}")
    private String approveRestrictedForOwnUser;

    @Value("${apps.agent.module.enabled}")
    private String agentModuleEnabled;

    @Value("${app.authentication.type}")
    private String authenticationType;

    @Value("${app.user.name.tail}")
    private String userNameTail;

    @Value("${app.allow.sending.email}")
    private Boolean allowSendingEmail;

    @Value("${apps.user.generated.password.length}")
    private String userGeneratedPasswordLength;

    @Value("${apps.user.auto.generated.password}")
    private Boolean autoGeneratedPasswordEnabled;

    @Value("${apps.crib.retail.credit.facility.view.limit}")
    private Integer cribFacilityViewLimit;

    @Value("${apps.dashboard.time.period.days}")
    private Integer dashboardTimePeriodDays;

    @Value("${apps.cas.application.manager.work.class}")
    private String managerWorkClass;

    @Value("${apps.authentication.sso}")
    private String isSSOLogin;

    @Value("${apps.authentication.ssoRedirectUri}")
    private String ssoRedirectUri;

    @Value("${apps.authentication.ssoLogoutRedirectUri}")
    private String ssoLogoutRedirectUri;

    @Value("${apps.cas.image.upload.custom.size.limits:}")
    private String imageUploadCustomSizeLimits;

    @Value("${apps.cas.context.path.microServiceURL}")
    private String leadContextPath;

    public String getImageUploadCustomSizeLimits() {
        return imageUploadCustomSizeLimits;
    }

    public void setImageUploadCustomSizeLimits(String imageUploadCustomSizeLimits) {
        this.imageUploadCustomSizeLimits = imageUploadCustomSizeLimits;
    }

    public String getPrivateKeyDerAbsolutePath() {
        return privateKeyDerAbsolutePath;
    }

    public void setPrivateKeyDerAbsolutePath(String privateKeyDerAbsolutePath) {
        this.privateKeyDerAbsolutePath = privateKeyDerAbsolutePath;
    }

    public String getPublicKeyDerAbsolutePath() {
        return publicKeyDerAbsolutePath;
    }

    public void setPublicKeyDerAbsolutePath(String publicKeyDerAbsolutePath) {
        this.publicKeyDerAbsolutePath = publicKeyDerAbsolutePath;
    }

    public String getPublicKeyPemAbsolutePath() {
        return publicKeyPemAbsolutePath;
    }

    public void setPublicKeyPemAbsolutePath(String publicKeyPemAbsolutePath) {
        this.publicKeyPemAbsolutePath = publicKeyPemAbsolutePath;
    }

    public String getApiPrefix() {
        return apiPrefix;
    }

    public void setApiPrefix(String apiPrefix) {
        this.apiPrefix = apiPrefix;
    }

    public String getStaticResourcesPath() {
        return staticResourcesPath;
    }

    public void setStaticResourcesPath(String staticResourcesPath) {
        this.staticResourcesPath = staticResourcesPath;
    }

    public Boolean getSecurityEnabled() {
        if (isSecurityEnabled == null) {
            isSecurityEnabled = true;
        }
        return isSecurityEnabled;
    }

    public void setSecurityEnabled(Boolean securityEnabled) {
        isSecurityEnabled = securityEnabled;
    }

    public String getImageUploadMaxSizeMB() {
        return imageUploadMaxSizeMB;
    }

    public void setImageUploadMaxSizeMB(String imageUploadMaxSizeMB) {
        this.imageUploadMaxSizeMB = imageUploadMaxSizeMB;
    }

    public String getImageUploadAllowedExtensions() {
        return imageUploadAllowedExtensions;
    }

    public void setImageUploadAllowedExtensions(String imageUploadAllowedExtensions) {
        this.imageUploadAllowedExtensions = imageUploadAllowedExtensions;
    }

    public String getApplicationCode() {
        return applicationCode;
    }

    public void setApplicationCode(String applicationCode) {
        this.applicationCode = applicationCode;
    }

    public String getLdapServerURL() {
        return ldapServerURL;
    }

    public void setLdapServerURL(String ldapServerURL) {
        this.ldapServerURL = ldapServerURL;
    }

    public String getLdapUserContext() {
        return ldapUserContext;
    }

    public void setLdapUserContext(String ldapUserContext) {
        this.ldapUserContext = ldapUserContext;
    }

    public String getTcpIpConfigEnabled() {
        return tcpIpConfigEnabled;
    }

    public void setTcpIpConfigEnabled(String tcpIpConfigEnabled) {
        this.tcpIpConfigEnabled = tcpIpConfigEnabled;
    }

    public String getNodesInfo() {
        return nodesInfo;
    }

    public void setNodesInfo(String nodesInfo) {
        this.nodesInfo = nodesInfo;
    }

    public Boolean getApproveRestrictedForOwnUser() {
        if (approveRestrictedForOwnUser == null) {
            return false;
        }
        return Boolean.valueOf(this.approveRestrictedForOwnUser);
    }

    public void setApproveRestrictedForOwnUser(String approveRestrictedForOwnUser) {
        this.approveRestrictedForOwnUser = approveRestrictedForOwnUser;
    }

    public String getAgentModuleEnabled() {
        return agentModuleEnabled;
    }

    public void setAgentModuleEnabled(String agentModuleEnabled) {
        this.agentModuleEnabled = agentModuleEnabled;
    }

    public boolean isAgentModuleEnabled() {
        return this.agentModuleEnabled != null ? Boolean.valueOf(this.agentModuleEnabled) : false;
    }

    public String getAuthenticationType() {
        return authenticationType;
    }

    public String getUserNameTail() {
        return userNameTail;
    }

    public Boolean isAllowSendingEmail() {
        return allowSendingEmail;
    }

    public String getUserGeneratedPasswordLength() {
        return userGeneratedPasswordLength;
    }

    public Boolean isAutoGeneratedPasswordEnabled() {
        return autoGeneratedPasswordEnabled;
    }

    public Integer getCribFacilityViewLimit() {
        return cribFacilityViewLimit;
    }

    public Integer getDashboardTimePeriodDays() {
        return dashboardTimePeriodDays;
    }

    public void setDashboardTimePeriodDays(Integer dashboardTimePeriodDays) {
        this.dashboardTimePeriodDays = dashboardTimePeriodDays;
    }

    public String getManagerWorkClass() {
        return managerWorkClass;
    }

    public void setManagerWorkClass(String managerWorkClass) {
        this.managerWorkClass = managerWorkClass;
    }

    public String getSsoRedirectUri() {
        return ssoRedirectUri;
    }

    public void setSsoRedirectUri(String ssoRedirectUri) {
        this.ssoRedirectUri = ssoRedirectUri;
    }

    public String getSsoLogoutRedirectUri() {
        return ssoLogoutRedirectUri;
    }

    public void setSsoLogoutRedirectUri(String ssoLogoutRedirectUri) {
        this.ssoLogoutRedirectUri = ssoLogoutRedirectUri;
    }

    public String getIsSSOLogin() {
        return isSSOLogin;
    }

    public void setIsSSOLogin(String isSSOLogin) {
        this.isSSOLogin = isSSOLogin;
    }

    public String getLeadContextPath() {
        return leadContextPath;
    }

    public void setLeadContextPath(String leadContextPath) {
        this.leadContextPath = leadContextPath;
    }
}
